- name: Create Valheim-LN
  hosts: localhost
  vars_files:
    - ./group_vars/vars.yml
  tasks:
    - name: Valheim-LN
      linode.cloud.instance:
        api_token: "{{ api_token }}"
        label: valheim-ln
        type: g6-dedicated-4
        region: ap-west
        image: linode/ubuntu22.10
        root_pass: "{{ password }}"
        state: present
      register: linode_instance

    - name: Add linode instance to hosts
      add_host:
        hostname: "{{ linode_instance.instance.ipv4 | first }}"
        groupname: linode_instances

    - name: Update inventory file with instance ip
      community.general.ini_file:
        allow_no_value: true
        no_extra_spaces: true
        path: /root/development/custom_inventory.ini
        section: linode_instances
        option: "{{ linode_instance.instance.ipv4 | first }}"
        state: present

    - name: Update inventory file with ansible collection
      community.general.ini_file:
        allow_no_value: true
        no_extra_spaces: true
        path: /root/development/custom_inventory.ini
        section: all:vars
        option: "ansible_connection"
        value: "ssh"
        state: present

    - name: Update inventory file with ssh user
      community.general.ini_file:
        allow_no_value: true
        no_extra_spaces: true
        path: /root/development/custom_inventory.ini
        section: all:vars
        option: "ansible_user"
        value: "root"
        state: present

    - name: Update inventory file with ssh password
      community.general.ini_file:
        allow_no_value: true
        no_extra_spaces: true
        path: /root/development/custom_inventory.ini
        section: all:vars
        option: "ansible_ssh_pass"
        value: "{{ password }}"
        state: present

    - name: Wait for linode instance to be running
      wait_for:
        port: 22
        host: '{{ linode_instance.instance.ipv4 | first }}'
        search_regex: OpenSSH
        delay: 10
